version: 2

updates:
- package-ecosystem: pip
  directory: "/REQUIREMENTS.development.txt"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: pip
  directory: "/REQUIREMENTS.linting.txt"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: pip
  directory: "/REQUIREMENTS.packaging.txt"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: pip
  directory: "/REQUIREMENTS.testing.txt"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
